service: puppet

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: default

functions:
  puppet:
    handler: dist/puppet.handler
    events:
      - http: ANY /puppet
      - http: 'ANY {proxy+}'
